name: CI/CD - Build & Deploy Backend + Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ############################################
      # AWS login configuration
      ############################################
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      ############################################
      # Set Image TAG: First 7 characters of Git commit
      ############################################
      - run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      ############################################
      # Backend
      ############################################
      - name: Build Backend Image
        run: |
          docker build -t backend:${IMAGE_TAG} ./backend
          docker tag backend:${IMAGE_TAG} ${{ steps.login-ecr.outputs.registry }}/rag-chatbot-backend:${IMAGE_TAG}
          docker push ${{ steps.login-ecr.outputs.registry }}/rag-chatbot-backend:${IMAGE_TAG}

      - name: Update Backend ECS Service
        run: |
          aws ecs update-service \
            --cluster rag-chatbot-cluster \
            --service rag-chatbot-backend-service \
            --force-new-deployment

      ############################################
      # Frontend
      ############################################
      - name: Build Frontend Image
        run: |
          docker build -t frontend:${IMAGE_TAG} ./frontend
          docker tag frontend:${IMAGE_TAG} ${{ steps.login-ecr.outputs.registry }}/rag-chatbot-frontend:${IMAGE_TAG}
          docker push ${{ steps.login-ecr.outputs.registry }}/rag-chatbot-frontend:${IMAGE_TAG}

      - name: Update Frontend ECS Service
        run: |
          aws ecs update-service \
            --cluster rag-chatbot-cluster \
            --service rag-chatbot-frontend-service \
            --force-new-deployment
